spring:
  application:
    name: IDaaS
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        server-addr: xxx.xxx.xxx.xxx:8848

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: gaoyifeng
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/IDaaS?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 1
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: xxxx
    appid: xxxx
    token: xxxx


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy