spring:
  application:
    name: IDaaS
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        server-addr: xxx.xxx.xxx.xxx:8848

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: gaoyifeng
    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/IDaaS?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 20
      min-idle: 1
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false